### ISSUE TITLE
[touchstone] structure the project

### ISSUE THREAD

**Issue by AmitKumarDas** [CloudByteStorages/touchstone#1]
@AbhiCloudbyte Please structure the project into specs, bugs, scripts etc.

The specs in turn can have below:
env.md
run.md
bug-reproduce.md
apply-patch.md
-- apply-patch-dr.md
-- apply-patch-iscsi-provisioning.md
report.md
bug-verify.md

The bugs can have shell scripts with the name equal to bug id. e.g. 7445.sh means a bug with id as 7445. It can have a function that returns a dictionary. This dictionary will be key:value pairs e.g.
desc: description of the bug
found_at: version of software
fixed_at: version of software

The scripts folder can have sub-folders e.g.
env/
run/
bug-reproduce/
apply-patch/
report/
bug-verify/

**Comment by AmitKumarDas** [comment]
I have tried to put new structure. Have a look.
The structure is now more or less complete.
Once initial source code are put into place, I shall close this issue.

**Comment by AbhiS1892** [comment]
The new structure is on its place now. Also, now we will be using 'escli' instead of 'tt'.
